### ISSUE TITLE
PHP CI/Unitテスト時にcacheが効いてなさそう

### ISSUE THREAD

**Issue by k-yamasaki-zakisan** [ysknsid25/otaku-tool#41]
## 気になった箇所
GitHub Actions上でCIをされている[PHPのunit test](https://github.com/ysknsid25/otaku-tool/blob/master/.github/workflows/PHP-UnitTest.yml)を実行時に
毎回composer installを実行していそうでした

キャッシュを入れられているので違和感を感じました
https://github.com/ysknsid25/otaku-tool/blob/master/.github/workflows/PHP-UnitTest.yml#L35

## 原因
デバックをしているわけではないので予想ですが
こちらのpathが間違っていることが原因ではないかと思いました
`./vendor` -> `./framework/vendor`
https://github.com/ysknsid25/otaku-tool/blob/master/.github/workflows/PHP-UnitTest.yml#L37

workflow post cache vendorの箇所のログ
`/usr/bin/tar: /home/runner/work/otaku-tool/otaku-tool/vendor: Cannot open: No such file or directory`

### 補足
あとキャッシュヒットしたときにautoloadが走らないのでappにクラスを追加した場合にエラーになるかもしれないので
`composer dump-autoload`
をいれたほうがいいかもです
[参考記事](https://qiita.com/ucan-lab/items/237d2058eb46ab657ae3#%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B33%E3%81%AE%E7%89%B9%E5%BE%B4:~:text=%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%8C%E5%88%A9%E7%94%A8%E3%81%95%E3%82%8C%E3%82%8B%E3%81%A8%E3%81%8D%E3%81%AFcomposer%20dump%2Dautoload%E3%81%8C%E5%AE%9F%E8%A1%8C%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84%E3%81%AE%E3%81%A7%E3%80%81%E5%88%A5%E9%80%94%E3%82%B9%E3%83%86%E3%83%83%E3%83%97%E3%82%92%E4%BD%9C%E3%81%A3%E3%81%A6%E3%81%82%E3%81%92%E3%82%8B%E5%BF%85%E8%A6%81%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82)

## FYI
ライブラリのバージョンが古いので警告が出ておりました
- `actions/checkout@v2  -> actions/checkout@v3`
  - https://github.com/actions/checkout#:~:text=%2D%20uses%3A-,actions/checkout%40v3,-with%3A%0A%20%20%20%20%23
- `actions/cache@v1  -> actions/cache@v3`
  - https://github.com/actions/cache#:~:text=primes%0A%20%20%20%20%20%20uses%3A-,actions/cache%40v3,-with%3A%0A%20%20%20%20%20%20%20%20path

## スクリーンショット
| 毎回composer installしてそう | cache先のフォルダがないと言われている | ライブラリが古いことによる警告 | 
| --- | --- | --- |
| ![スクリーンショット 2023-04-09 13 21 11](https://user-images.githubusercontent.com/55447682/230755214-70eba0f8-61a1-4180-a120-7217575e448c.png) | ![スクリーンショット 2023-04-09 13 54 23](https://user-images.githubusercontent.com/55447682/230755221-58daf680-0b4f-4268-bac3-7e2b1aa0fb1f.png) |  ![スクリーンショット 2023-04-09 13 17 47](https://user-images.githubusercontent.com/55447682/230755235-014e3a7e-3ce1-441d-821b-3a81dcc0884d.png) |

**Comment by ysknsid25** [comment]
issueありがとうございます！
こちらのissue、@k-yamasaki-zakisan のほうで対応しますか？
(面倒であれば私の方で見ていきます👍)

**Comment by k-yamasaki-zakisan** [comment]
正直このissuesの対応価値は低いと思ってます
（publicなのでActionsに料金はかかってないと思いますので...）

ただせっかくの機会なので@ysknsid25 さん自身がDevOps周りの実装やってみてもいいのかなと思いました

後お節介かもしれませんがphpstanやphp_cs_fixerなどでworkflowにlintやformatを入れていると品質担保に役に立つかなと思いました
参考例
- https://qiita.com/tumugin/items/9ea8b5439167b5368379
- https://qiita.com/kai_kou/items/e22cb6d693cdef041890

**Comment by ysknsid25** [comment]
@k-yamasaki-zakisan 

いえいえとんでもないです。
こういうアドバイスを外のコミュニティの方からいただきたくて、このプロジェクトを始めたというところがあるので感謝しかないです。

おっしゃるとおり、せっかくの機会なので自分で実装させてもらいます🙏
もしよければ、なにか困った時にこのissue上で相談させていただけると助かります🙇

**Comment by ysknsid25** [comment]
@k-yamasaki-zakisan 

お疲れ様です。
cache周りの問題に対して修正をおこなってみました。
もしお時間があれば、修正結果について[こちらのプルリク](https://github.com/ysknsid25/otaku-tool/pull/48)をレビューしていただけないでしょうか？
恐れ入りますがご確認よろしくお願いいたします。

**Comment by ysknsid25** [comment]
@k-yamasaki-zakisan
